/*
 * List of cgroup subsystems.
 *
 * DO NOT ADD ANY SUBSYSTEM WITHOUT EXPLICIT ACKS FROM CGROUP MAINTAINERS.
 */
#if IS_SUBSYS_ENABLED(CONFIG_CPUSETS) // CONFIG_CPUSETS=n
SUBSYS(cpuset)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_DEBUG) // CONFIG_CGROUP_DEBUG=y
// ARM10C 20150822
// SUBSYS(debug): debug_subsys_id,
// ARM10C 20150822
// SUBSYS(debug): [debug_subsys_id] = &debug_subsys,
SUBSYS(debug)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_SCHED) // CONFIG_CGROUP_SCHED=y
// ARM10C 20150822
// SUBSYS(cpu_cgroup): cpu_cgroup_subsys_id,
// ARM10C 20150822
// SUBSYS(cpu_cgroup): [cpu_cgroup_subsys_id] = &cpu_cgroup_subsys,
SUBSYS(cpu_cgroup)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_CPUACCT) // CONFIG_CGROUP_CPUACCT=y
// ARM10C 20150822
// SUBSYS(cpuacct): cpuacct_subsys_id,
// ARM10C 20150822
// SUBSYS(cpuacct): [cpuacct_subsys_id] = &cpuacct_subsys,
SUBSYS(cpuacct)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_MEMCG) // CONFIG_MEMCG=n
SUBSYS(mem_cgroup)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_DEVICE) // CONFIG_CGROUP_DEVICE=n
SUBSYS(devices)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_FREEZER) // CONFIG_CGROUP_FREEZER=y
// ARM10C 20150822
// SUBSYS(freezer): freezer_subsys_id,
// ARM10C 20150822
// SUBSYS(freezer): [freezer_subsys_id] = &freezer_subsys,
SUBSYS(freezer)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_NET_CLS_CGROUP) // CONFIG_NET_CLS_CGROUP=n
SUBSYS(net_cls)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_BLK_CGROUP) // CONFIG_BLK_CGROUP=n
SUBSYS(blkio)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_PERF) // CONFIG_CGROUP_PERF=n
SUBSYS(perf)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_NETPRIO_CGROUP) // CONFIG_NETPRIO_CGROUP=n
SUBSYS(net_prio)
#endif

#if IS_SUBSYS_ENABLED(CONFIG_CGROUP_HUGETLB) // CONFIG_CGROUP_HUGETLB=n
SUBSYS(hugetlb)
#endif
/*
 * DO NOT ADD ANY SUBSYSTEM WITHOUT EXPLICIT ACKS FROM CGROUP MAINTAINERS.
 */
