#ifndef VM_EVENT_ITEM_H_INCLUDED
#define VM_EVENT_ITEM_H_INCLUDED

#ifdef CONFIG_ZONE_DMA // CONFIG_ZONE_DMA=n
#define DMA_ZONE(xx) xx##_DMA,
#else
// ARM10C 20140405
#define DMA_ZONE(xx)
#endif

#ifdef CONFIG_ZONE_DMA32 // CONFIG_ZONE_DMA32=n
#define DMA32_ZONE(xx) xx##_DMA32,
#else
// ARM10C 20140405
#define DMA32_ZONE(xx)
#endif

#ifdef CONFIG_HIGHMEM // CONFIG_HIGHMEM=y
// ARM10C 20140405
// HIGHMEM_ZONE(PGALLOC): PGALLOC_HIGH
#define HIGHMEM_ZONE(xx) , xx##_HIGH
#else
#define HIGHMEM_ZONE(xx)
#endif

// ARM10C 20140405
// DMA_ZONE(PGALLOC):
// DMA32_ZONE(PGALLOC):
// HIGHMEM_ZONE(PGALLOC): PGALLOC_HIGH
//
// FOR_ALL_ZONES(PGALLOC):
// PGALLOC_NORMAL PGALLOC_HIGH, PGALLOC_MOVABLE
#define FOR_ALL_ZONES(xx) DMA_ZONE(xx) DMA32_ZONE(xx) xx##_NORMAL HIGHMEM_ZONE(xx) , xx##_MOVABLE

// ARM10C 20140405
enum vm_event_item { PGPGIN, PGPGOUT, PSWPIN, PSWPOUT,
		FOR_ALL_ZONES(PGALLOC), // PGALLOC_NORMAL, PGALLOC_HIGH, PGALLOC_MOVABLE,
		PGFREE, PGACTIVATE, PGDEACTIVATE, // PGFREE: 7
		PGFAULT, PGMAJFAULT,
		FOR_ALL_ZONES(PGREFILL), // PGREFILL_NORMAL, PGREFILL_HIGH, PGREFILL_MOVABLE,
		FOR_ALL_ZONES(PGSTEAL_KSWAPD), // PGSTEAL_KSWAPD_NORMAL, PGSTEAL_KSWAPD_HIGH, PGSTEAL_KSWAPD_MOVABLE,
		FOR_ALL_ZONES(PGSTEAL_DIRECT), // PGSTEAL_DIRECT_NORMAL, PGSTEAL_DIRECT_HIGH, PGSTEAL_DIRECT_MOVABLE,
		FOR_ALL_ZONES(PGSCAN_KSWAPD), // PGSCAN_KSWAPD_NORMAL, PGSCAN_KSWAPD_HIGH, PGSCAN_KSWAPD_MOVABLE,
		FOR_ALL_ZONES(PGSCAN_DIRECT), // PGSCAN_DIRECT_NORMAL, PGSCAN_DIRECT_HIGH, PGSCAN_DIRECT_MOVABLE,

		PGSCAN_DIRECT_THROTTLE, // PGSCAN_DIRECT_THROTTLE: 27
#ifdef CONFIG_NUMA // CONFIG_NUMA=n
		PGSCAN_ZONE_RECLAIM_FAILED,
#endif
		PGINODESTEAL, SLABS_SCANNED, KSWAPD_INODESTEAL,
		KSWAPD_LOW_WMARK_HIT_QUICKLY, KSWAPD_HIGH_WMARK_HIT_QUICKLY,
		PAGEOUTRUN, ALLOCSTALL, PGROTATED, // PGROTATED: 35
#ifdef CONFIG_NUMA_BALANCING // CONFIG_NUMA_BALANCING=n
		NUMA_PTE_UPDATES,
		NUMA_HUGE_PTE_UPDATES,
		NUMA_HINT_FAULTS,
		NUMA_HINT_FAULTS_LOCAL,
		NUMA_PAGE_MIGRATE,
#endif
#ifdef CONFIG_MIGRATION // CONFIG_MIGRATION=y
		PGMIGRATE_SUCCESS, PGMIGRATE_FAIL, // PGMIGRATE_FAIL: 37
#endif
#ifdef CONFIG_COMPACTION // CONFIG_COMPACTION=y
		COMPACTMIGRATE_SCANNED, COMPACTFREE_SCANNED,
		COMPACTISOLATED,
		COMPACTSTALL, COMPACTFAIL, COMPACTSUCCESS, // COMPACTSUCCESS: 43
#endif
#ifdef CONFIG_HUGETLB_PAGE // CONFIG_HUGETLB_PAGE=n
		HTLB_BUDDY_PGALLOC, HTLB_BUDDY_PGALLOC_FAIL,
#endif
		UNEVICTABLE_PGCULLED,	/* culled to noreclaim list */
		UNEVICTABLE_PGSCANNED,	/* scanned for reclaimability */
		UNEVICTABLE_PGRESCUED,	/* rescued from noreclaim list */
		UNEVICTABLE_PGMLOCKED,
		UNEVICTABLE_PGMUNLOCKED,
		UNEVICTABLE_PGCLEARED,	/* on COW, page truncate */
		UNEVICTABLE_PGSTRANDED,	/* unable to isolate on unlock */
#ifdef CONFIG_TRANSPARENT_HUGEPAGE // CONFIG_TRANSPARENT_HUGEPAGE=n
		THP_FAULT_ALLOC,
		THP_FAULT_FALLBACK,
		THP_COLLAPSE_ALLOC,
		THP_COLLAPSE_ALLOC_FAILED,
		THP_SPLIT,
		THP_ZERO_PAGE_ALLOC,
		THP_ZERO_PAGE_ALLOC_FAILED,
#endif
#ifdef CONFIG_SMP
		NR_TLB_REMOTE_FLUSH,	/* cpu tried to flush others' tlbs */
		NR_TLB_REMOTE_FLUSH_RECEIVED,/* cpu received ipi for flush */
#endif
		NR_TLB_LOCAL_FLUSH_ALL,
		NR_TLB_LOCAL_FLUSH_ONE,
		NR_VM_EVENT_ITEMS // NR_VM_EVENT_ITEMS: 51
};

#endif		/* VM_EVENT_ITEM_H_INCLUDED */
